# Generated by Django 4.2.4 on 2023-08-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cutomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cutomer',
        ),
    ]
